package seed

import "github.com/seanmeyer/powder-hunter/domain"

// RegionWithResorts pairs a region with the ski areas that share its weather.
type RegionWithResorts struct {
	Region  domain.Region
	Resorts []domain.Resort
}

// Regions returns all predefined regions and their resorts. Thresholds reflect
// the friction cost of reaching each tier: local resorts justify a trip on
// lighter snow; flight destinations need a meaningful storm to be worth the cost.
func Regions() []RegionWithResorts {
	return []RegionWithResorts{

		// ── Colorado: local tier (I-70 corridor, <2h from Denver) ─────────────

		{
			Region: domain.Region{
				ID:                  "co_summit_county",
				Name:                "Summit County, CO",
				Latitude:            39.4817,
				Longitude:           -106.0384,
				FrictionTier:        domain.FrictionLocal,
				NearThresholdCM:     20,
				ExtendedThresholdCM: 30,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "breckenridge",
					RegionID:        "co_summit_county",
					Name:            "Breckenridge",
					Latitude:        39.4817,
					Longitude:       -106.0384,
					ElevationM:      3914,
					PassAffiliation: "epic",
					VerticalDropM:   1035,
					LiftCount:       35,
					Metadata: map[string]string{
						"reputation":       "iconic Colorado destination, massive above-treeline bowl terrain",
						"terrain_character": "wide open bowls above treeline plus groomed cruisers; can be wind-scoured up high",
						"access_notes":     "Hwy 9 from I-70 at Frisco, ~1.5h from Denver; free town shuttles once there",
					},
				},
				{
					ID:              "keystone",
					RegionID:        "co_summit_county",
					Name:            "Keystone",
					Latitude:        39.6086,
					Longitude:       -105.9536,
					ElevationM:      3658,
					PassAffiliation: "epic",
					VerticalDropM:   868,
					LiftCount:       21,
					Metadata: map[string]string{
						"reputation":       "family-friendly, excellent grooming, night skiing",
						"terrain_character": "front-side groomers plus North Peak and Outback bowls for more advanced terrain",
						"access_notes":     "US-6 from I-70 at exit 205, ~1.5h from Denver",
					},
				},
				{
					ID:              "arapahoe_basin",
					RegionID:        "co_summit_county",
					Name:            "Arapahoe Basin",
					Latitude:        39.6428,
					Longitude:       -105.8714,
					ElevationM:      3979,
					PassAffiliation: "ikon",
					VerticalDropM:   722,
					LiftCount:       9,
					Metadata: map[string]string{
						"reputation":       "highest base in CO, legendary late-season skiing into June, no-frills soul mountain",
						"terrain_character": "high alpine bowls, steep chutes, exposed ridgelines; not for beginners",
						"access_notes":     "US-6 over Loveland Pass from I-70, ~1.5h from Denver; road can close in storms",
					},
				},
				{
					ID:              "copper_mountain",
					RegionID:        "co_summit_county",
					Name:            "Copper Mountain",
					Latitude:        39.5022,
					Longitude:       -106.1500,
					ElevationM:      3753,
					PassAffiliation: "ikon",
					VerticalDropM:   894,
					LiftCount:       23,
					Metadata: map[string]string{
						"reputation":       "natural terrain separation by ability level, less crowded than Breck or Vail",
						"terrain_character": "expert terrain on East Village side, cruisers in center, beginner on west; natural fall-line skiing",
						"access_notes":     "I-70 exit 195, ~1.5h from Denver; ski-in/ski-out village",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "co_vail_valley",
				Name:                "Vail Valley, CO",
				Latitude:            39.6433,
				Longitude:           -106.3781,
				FrictionTier:        domain.FrictionLocal,
				NearThresholdCM:     20,
				ExtendedThresholdCM: 30,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "vail",
					RegionID:        "co_vail_valley",
					Name:            "Vail",
					Latitude:        39.6433,
					Longitude:       -106.3781,
					ElevationM:      3527,
					PassAffiliation: "epic",
					VerticalDropM:   1087,
					LiftCount:       31,
					Metadata: map[string]string{
						"reputation":       "world-class back bowls, one of the largest ski areas in North America",
						"terrain_character": "legendary Back Bowls and Blue Sky Basin for powder; front side has every ability level",
						"access_notes":     "I-70 exit 176, ~2h from Denver; Vail village is walkable and ski-in/ski-out",
					},
				},
				{
					ID:              "beaver_creek",
					RegionID:        "co_vail_valley",
					Name:            "Beaver Creek",
					Latitude:        39.6042,
					Longitude:       -106.5164,
					ElevationM:      3480,
					PassAffiliation: "epic",
					VerticalDropM:   1116,
					LiftCount:       25,
					Metadata: map[string]string{
						"reputation":       "exclusive, manicured, Birds of Prey World Cup race venue; less crowded than Vail",
						"terrain_character": "steep groomed runs, Grouse Mountain expert terrain, excellent high-speed cruisers",
						"access_notes":     "I-70 exit 167, ~2h from Denver; free shuttle from Avon; village is car-free",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "co_winter_park",
				Name:                "Winter Park Area, CO",
				Latitude:            39.8868,
				Longitude:           -105.7625,
				FrictionTier:        domain.FrictionLocal,
				NearThresholdCM:     20,
				ExtendedThresholdCM: 30,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "winter_park",
					RegionID:        "co_winter_park",
					Name:            "Winter Park",
					Latitude:        39.8868,
					Longitude:       -105.7625,
					ElevationM:      2804,
					PassAffiliation: "ikon",
					VerticalDropM:   701,
					LiftCount:       25,
					Metadata: map[string]string{
						"reputation":       "Denver locals' mountain, excellent tree skiing, consistently high snowfall on the divide",
						"terrain_character": "Mary Jane side has legendary moguls and trees; main mountain has groomers for all levels",
						"access_notes":     "US-40 over Berthoud Pass, ~1.5h from Denver; Amtrak Winter Park Express runs Fri-Sun",
					},
				},
			},
		},

		// ── Colorado: regional_driveable (4+ hours from Denver) ───────────────

		{
			Region: domain.Region{
				ID:                  "co_aspen",
				Name:                "Aspen Area, CO",
				Latitude:            39.1911,
				Longitude:           -106.8175,
				FrictionTier:        domain.FrictionRegionalDriveable,
				NearThresholdCM:     36,
				ExtendedThresholdCM: 51,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "aspen_mountain",
					RegionID:        "co_aspen",
					Name:            "Aspen Mountain",
					Latitude:        39.1837,
					Longitude:       -106.8198,
					ElevationM:      3418,
					PassAffiliation: "ikon",
					VerticalDropM:   1005,
					LiftCount:       8,
					Metadata: map[string]string{
						"reputation":       "no beginner terrain, serious expert-oriented mountain with iconic Ajax status",
						"terrain_character": "steep groomers, famous Silver Queen gondola, consistent expert terrain throughout",
						"access_notes":     "4h from Denver via I-70 and CO-82 over Independence Pass (closed in winter — use Glenwood Canyon route, adds ~30min)",
					},
				},
				{
					ID:              "aspen_highlands",
					RegionID:        "co_aspen",
					Name:            "Aspen Highlands",
					Latitude:        39.2072,
					Longitude:       -106.8667,
					ElevationM:      3606,
					PassAffiliation: "ikon",
					VerticalDropM:   1080,
					LiftCount:       5,
					Metadata: map[string]string{
						"reputation":       "Highland Bowl is a bucket-list hike-to zone; best expert terrain in Aspen area",
						"terrain_character": "Highland Bowl requires 30-45min boot pack for 500 acres of ungroomed high-alpine powder",
						"access_notes":     "free shuttle from Rubey Park in Aspen town; same drive as Aspen Mountain",
					},
				},
				{
					ID:              "buttermilk",
					RegionID:        "co_aspen",
					Name:            "Buttermilk",
					Latitude:        39.2108,
					Longitude:       -106.9389,
					ElevationM:      2987,
					PassAffiliation: "ikon",
					VerticalDropM:   576,
					LiftCount:       9,
					Metadata: map[string]string{
						"reputation":       "beginner/intermediate mountain, X Games venue; good for learning or mellow days",
						"terrain_character": "gentle terrain, terrain parks, X-Games superpipe; not a storm-chasing destination",
						"access_notes":     "free shuttle from Rubey Park; same drive as Aspen Mountain",
					},
				},
				{
					ID:              "snowmass",
					RegionID:        "co_aspen",
					Name:            "Snowmass",
					Latitude:        39.2086,
					Longitude:       -106.9497,
					ElevationM:      3538,
					PassAffiliation: "ikon",
					VerticalDropM:   1344,
					LiftCount:       21,
					Metadata: map[string]string{
						"reputation":       "largest of the four Aspen mountains, massive vertical, great for families and experts alike",
						"terrain_character": "Hanging Valley Headwall for experts, long groomed runs, excellent tree skiing in storms",
						"access_notes":     "free shuttle from Aspen; has its own ski-in/ski-out village at base",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "co_steamboat",
				Name:                "Steamboat Area, CO",
				Latitude:            40.4572,
				Longitude:           -106.8045,
				FrictionTier:        domain.FrictionRegionalDriveable,
				NearThresholdCM:     36,
				ExtendedThresholdCM: 51,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "steamboat",
					RegionID:        "co_steamboat",
					Name:            "Steamboat",
					Latitude:        40.4572,
					Longitude:       -106.8045,
					ElevationM:      3221,
					PassAffiliation: "ikon",
					VerticalDropM:   884,
					LiftCount:       18,
					Metadata: map[string]string{
						"reputation":       "Champagne Powder trademark; legendary tree skiing in storm cycles; cowboy vibe",
						"terrain_character": "famous gladed tree runs like Shadows and Twilight; consistent storm totals off Park Range",
						"access_notes":     "3.5h from Denver via US-40 over Rabbit Ears Pass; direct flights to Hayden (HDN) from many hubs",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "co_telluride",
				Name:                "Telluride Area, CO",
				Latitude:            37.9375,
				Longitude:           -107.8123,
				FrictionTier:        domain.FrictionRegionalDriveable,
				NearThresholdCM:     36,
				ExtendedThresholdCM: 51,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "telluride",
					RegionID:        "co_telluride",
					Name:            "Telluride",
					Latitude:        37.9375,
					Longitude:       -107.8123,
					ElevationM:      3835,
					PassAffiliation: "ikon",
					VerticalDropM:   1257,
					LiftCount:       19,
					Metadata: map[string]string{
						"reputation":       "remote, stunning box canyon setting, world-class expert terrain, low crowds",
						"terrain_character": "Revelation Bowl and Gold Hill for experts; free gondola connects mountain village to historic town",
						"access_notes":     "6-7h from Denver via US-285 or I-70/550; closest airport is Telluride Regional (TEX) or Montrose (MTJ)",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "co_wolf_creek",
				Name:                "Wolf Creek / Pagosa Area, CO",
				Latitude:            37.4744,
				Longitude:           -106.7972,
				FrictionTier:        domain.FrictionRegionalDriveable,
				NearThresholdCM:     36,
				ExtendedThresholdCM: 51,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "wolf_creek",
					RegionID:        "co_wolf_creek",
					Name:            "Wolf Creek",
					Latitude:        37.4744,
					Longitude:       -106.7972,
					ElevationM:      3596,
					PassAffiliation: "independent",
					VerticalDropM:   609,
					LiftCount:       8,
					Metadata: map[string]string{
						"reputation":       "highest average snowfall in Colorado (~11m/year), no-frills local secret, powder guaranteed",
						"terrain_character": "dense glades, no base village crowds, terrain suits all abilities; go when it snows here",
						"access_notes":     "5-6h from Denver via US-160; passes close in big storms — arrive before the storm or after plowing",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "co_crested_butte",
				Name:                "Crested Butte Area, CO",
				Latitude:            38.8697,
				Longitude:           -106.9878,
				FrictionTier:        domain.FrictionRegionalDriveable,
				NearThresholdCM:     36,
				ExtendedThresholdCM: 51,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "crested_butte",
					RegionID:        "co_crested_butte",
					Name:            "Crested Butte",
					Latitude:        38.8697,
					Longitude:       -106.9878,
					ElevationM:      3707,
					PassAffiliation: "ikon",
					VerticalDropM:   801,
					LiftCount:       16,
					Metadata: map[string]string{
						"reputation":       "extreme terrain mecca, North Face double-blacks are genuinely committing; charming town",
						"terrain_character": "steepest in-bounds terrain in CO including Rambo, Peel, and Headwall; not a groomer mountain",
						"access_notes":     "4h from Denver via US-285 and CO-114; Gunnison (GUC) airport has seasonal service",
					},
				},
			},
		},

		// ── Utah ──────────────────────────────────────────────────────────────

		{
			Region: domain.Region{
				ID:                  "ut_wasatch_front",
				Name:                "Wasatch Front (Little Cottonwood / Big Cottonwood), UT",
				Latitude:            40.5886,
				Longitude:           -111.6508,
				FrictionTier:        domain.FrictionRegionalDriveable,
				NearThresholdCM:     36,
				ExtendedThresholdCM: 51,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "alta",
					RegionID:        "ut_wasatch_front",
					Name:            "Alta",
					Latitude:        40.5886,
					Longitude:       -111.6377,
					ElevationM:      3216,
					PassAffiliation: "ikon",
					VerticalDropM:   810,
					LiftCount:       11,
					Metadata: map[string]string{
						"reputation":       "skiers-only, legendary Utah powder, one of the best snowfall records in North America",
						"terrain_character": "high-alpine bowls, dense trees, consistent deep powder; no snowboarders by policy",
						"access_notes":     "Little Cottonwood Canyon can close in avalanche control — check UDOT; 45min from SLC airport",
					},
				},
				{
					ID:              "snowbird",
					RegionID:        "ut_wasatch_front",
					Name:            "Snowbird",
					Latitude:        40.5831,
					Longitude:       -111.6556,
					ElevationM:      3353,
					PassAffiliation: "ikon",
					VerticalDropM:   1066,
					LiftCount:       14,
					Metadata: map[string]string{
						"reputation":       "massive vertical, consistent deep powder, tram to 11,000ft, challenging terrain dominates",
						"terrain_character": "steep couloirs and bowls off Hidden Peak tram; Mineral Basin on back side; connects to Alta",
						"access_notes":     "Little Cottonwood Canyon — same road closure risk as Alta; 40min from SLC airport",
					},
				},
				{
					ID:              "brighton",
					RegionID:        "ut_wasatch_front",
					Name:            "Brighton",
					Latitude:        40.5986,
					Longitude:       -111.5831,
					ElevationM:      3108,
					PassAffiliation: "ikon",
					VerticalDropM:   518,
					LiftCount:       8,
					Metadata: map[string]string{
						"reputation":       "Big Cottonwood Canyon gem, night skiing, snowboarders welcome, less traffic than LCC",
						"terrain_character": "accessible powder terrain, good trees, connects to Solitude for combined touring",
						"access_notes":     "Big Cottonwood Canyon rarely closes; 45min from SLC; UT-190 generally passable",
					},
				},
				{
					ID:              "solitude",
					RegionID:        "ut_wasatch_front",
					Name:            "Solitude",
					Latitude:        40.6197,
					Longitude:       -111.5919,
					ElevationM:      2918,
					PassAffiliation: "ikon",
					VerticalDropM:   579,
					LiftCount:       9,
					Metadata: map[string]string{
						"reputation":       "low-key, true solitude (name is accurate), excellent powder in Honeycomb Canyon",
						"terrain_character": "Honeycomb Canyon expert terrain rivals LCC resorts; front side suits all abilities",
						"access_notes":     "Big Cottonwood Canyon, same road as Brighton; 45min from SLC",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "ut_park_city",
				Name:                "Park City Area, UT",
				Latitude:            40.6514,
				Longitude:           -111.5080,
				FrictionTier:        domain.FrictionRegionalDriveable,
				NearThresholdCM:     36,
				ExtendedThresholdCM: 51,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "park_city",
					RegionID:        "ut_park_city",
					Name:            "Park City Mountain",
					Latitude:        40.6514,
					Longitude:       -111.5080,
					ElevationM:      3048,
					PassAffiliation: "epic",
					VerticalDropM:   701,
					LiftCount:       41,
					Metadata: map[string]string{
						"reputation":       "largest ski resort in US, connects to Canyons, vast terrain for all levels",
						"terrain_character": "wide variety from beginner groomers to expert Jupiter Bowl; enormous terrain parks",
						"access_notes":     "35min from SLC airport via I-80/UT-224; I-80 stays open in most storms",
					},
				},
				{
					ID:              "deer_valley",
					RegionID:        "ut_park_city",
					Name:            "Deer Valley",
					Latitude:        40.6374,
					Longitude:       -111.4783,
					ElevationM:      2918,
					PassAffiliation: "ikon",
					VerticalDropM:   914,
					LiftCount:       21,
					Metadata: map[string]string{
						"reputation":       "skiers-only luxury resort, impeccable grooming, ski valets, no crowds, premium experience",
						"terrain_character": "meticulously groomed runs, Empire Canyon expert terrain, consistent quality top to bottom",
						"access_notes":     "35min from SLC airport; skiers-only policy (no snowboards); valet ski check standard",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "ut_ogden_valley",
				Name:                "Ogden Valley, UT",
				Latitude:            41.2161,
				Longitude:           -111.8569,
				FrictionTier:        domain.FrictionRegionalDriveable,
				NearThresholdCM:     36,
				ExtendedThresholdCM: 51,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "snowbasin",
					RegionID:        "ut_ogden_valley",
					Name:            "Snowbasin",
					Latitude:        41.2161,
					Longitude:       -111.8569,
					ElevationM:      2917,
					PassAffiliation: "independent",
					VerticalDropM:   917,
					LiftCount:       12,
					Metadata: map[string]string{
						"reputation":       "underrated gem, 2002 Olympics DH venue, world-class steep terrain, low crowds",
						"terrain_character": "John Paul and Strawberry expert zones are serious; excellent grooming on Allen Peak",
						"access_notes":     "1h from SLC airport via I-15 and UT-226; road rarely closes; free parking",
					},
				},
				{
					ID:              "powder_mountain",
					RegionID:        "ut_ogden_valley",
					Name:            "Powder Mountain",
					Latitude:        41.3783,
					Longitude:       -111.7797,
					ElevationM:      2744,
					PassAffiliation: "independent",
					VerticalDropM:   548,
					LiftCount:       7,
					Metadata: map[string]string{
						"reputation":       "largest skiable acreage in US, snow cat access, intentionally limited lift capacity",
						"terrain_character": "extensive sidecountry via snowcat, consistent deep snow, low skier density by design",
						"access_notes":     "1h from SLC; cat skiing tickets sold separately; intentionally rustic experience",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "ut_southern",
				Name:                "Southern Utah",
				Latitude:            37.6978,
				Longitude:           -112.8494,
				FrictionTier:        domain.FrictionRegionalDriveable,
				NearThresholdCM:     36,
				ExtendedThresholdCM: 51,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "brian_head",
					RegionID:        "ut_southern",
					Name:            "Brian Head",
					Latitude:        37.6978,
					Longitude:       -112.8494,
					ElevationM:      3322,
					PassAffiliation: "independent",
					VerticalDropM:   541,
					LiftCount:       8,
					Metadata: map[string]string{
						"reputation":       "highest base elevation in Utah, surprisingly good powder, accessible from Las Vegas",
						"terrain_character": "small but high-altitude; good storm snow; suits families and intermediate skiers",
						"access_notes":     "3h from Las Vegas or 4h from SLC; US-143 accesses the resort",
					},
				},
			},
		},

		// ── Montana / Wyoming ─────────────────────────────────────────────────

		{
			Region: domain.Region{
				ID:                  "mt_big_sky",
				Name:                "Big Sky Area, MT",
				Latitude:            45.2838,
				Longitude:           -111.4015,
				FrictionTier:        domain.FrictionRegionalDriveable,
				NearThresholdCM:     36,
				ExtendedThresholdCM: 51,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "big_sky",
					RegionID:        "mt_big_sky",
					Name:            "Big Sky",
					Latitude:        45.2838,
					Longitude:       -111.4015,
					ElevationM:      3403,
					PassAffiliation: "ikon",
					VerticalDropM:   1447,
					LiftCount:       39,
					Metadata: map[string]string{
						"reputation":       "\"the biggest skiing in America\", massive terrain, low skier density even on holidays",
						"terrain_character": "Lone Peak tram to 11,166ft, Big Couloir expert zone, vast intermediate and expert terrain",
						"access_notes":     "1h from Bozeman (BZN) airport; Bozeman well-served by direct flights from major hubs",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "wy_jackson_hole",
				Name:                "Jackson Hole Area, WY",
				Latitude:            43.5875,
				Longitude:           -110.8275,
				FrictionTier:        domain.FrictionRegionalDriveable,
				NearThresholdCM:     36,
				ExtendedThresholdCM: 51,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "jackson_hole",
					RegionID:        "wy_jackson_hole",
					Name:            "Jackson Hole Mountain Resort",
					Latitude:        43.5875,
					Longitude:       -110.8275,
					ElevationM:      3185,
					PassAffiliation: "ikon",
					VerticalDropM:   1262,
					LiftCount:       13,
					Metadata: map[string]string{
						"reputation":       "steepest major resort in North America, legendary expert terrain, cult status powder days",
						"terrain_character": "Corbet's Couloir, Hobacks, Tetons backdrop; committed expert mountain with accessible alternatives",
						"access_notes":     "Jackson Hole Airport (JAC) is inside Grand Teton NP, 20min to base; direct flights from major cities",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "mt_whitefish",
				Name:                "Whitefish Area, MT",
				Latitude:            48.4864,
				Longitude:           -114.3553,
				FrictionTier:        domain.FrictionRegionalDriveable,
				NearThresholdCM:     36,
				ExtendedThresholdCM: 51,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "whitefish",
					RegionID:        "mt_whitefish",
					Name:            "Whitefish Mountain Resort",
					Latitude:        48.4864,
					Longitude:       -114.3553,
					ElevationM:      2152,
					PassAffiliation: "independent",
					VerticalDropM:   771,
					LiftCount:       14,
					Metadata: map[string]string{
						"reputation":       "charming Montana town, consistent snowfall, overlooked Pacific storm track, affordable",
						"terrain_character": "great tree skiing on north-facing runs, good powder preservation, all ability levels",
						"access_notes":     "30min from Glacier Park International (FCA); Amtrak Empire Builder stops in Whitefish",
					},
				},
			},
		},

		// ── New Mexico ────────────────────────────────────────────────────────

		{
			Region: domain.Region{
				ID:                  "nm_taos",
				Name:                "Taos Area, NM",
				Latitude:            36.5953,
				Longitude:           -105.4469,
				FrictionTier:        domain.FrictionRegionalDriveable,
				NearThresholdCM:     36,
				ExtendedThresholdCM: 51,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "taos_ski_valley",
					RegionID:        "nm_taos",
					Name:            "Taos Ski Valley",
					Latitude:        36.5953,
					Longitude:       -105.4469,
					ElevationM:      3804,
					PassAffiliation: "ikon",
					VerticalDropM:   868,
					LiftCount:       15,
					Metadata: map[string]string{
						"reputation":       "challenging terrain, deep powder from SW storm track, unique culture, underrated internationally",
						"terrain_character": "steep and deep; Kachina Peak for expert hike-to terrain; great ski school tradition",
						"access_notes":     "2.5h from Albuquerque (ABQ) or 1.5h from Santa Fe; NM-150 into the valley",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "nm_santa_fe",
				Name:                "Santa Fe Area, NM",
				Latitude:            35.7914,
				Longitude:           -105.7892,
				FrictionTier:        domain.FrictionRegionalDriveable,
				NearThresholdCM:     36,
				ExtendedThresholdCM: 51,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "ski_santa_fe",
					RegionID:        "nm_santa_fe",
					Name:            "Ski Santa Fe",
					Latitude:        35.7914,
					Longitude:       -105.7892,
					ElevationM:      3962,
					PassAffiliation: "independent",
					VerticalDropM:   607,
					LiftCount:       7,
					Metadata: map[string]string{
						"reputation":       "high altitude (top at 12,053ft), quick day trip from Santa Fe, surprising terrain quality",
						"terrain_character": "above treeline bowls when open, trees below; better in good snow years",
						"access_notes":     "16mi from Santa Fe Plaza via Hyde Park Road; 1h from Albuquerque",
					},
				},
			},
		},

		// ── California / Tahoe ────────────────────────────────────────────────

		{
			Region: domain.Region{
				ID:                  "ca_north_tahoe",
				Name:                "North Lake Tahoe, CA",
				Latitude:            39.1969,
				Longitude:           -120.2358,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "palisades_tahoe",
					RegionID:        "ca_north_tahoe",
					Name:            "Palisades Tahoe",
					Latitude:        39.1969,
					Longitude:       -120.2358,
					ElevationM:      2739,
					PassAffiliation: "ikon",
					VerticalDropM:   1676,
					LiftCount:       42,
					Metadata: map[string]string{
						"reputation":       "largest in Tahoe, 1960 Olympics venue, KT-22 as premier expert lift in North America",
						"terrain_character": "KT-22 expert faces, vast intermediate terrain, connects to Alpine Meadows via gondola",
						"access_notes":     "4.5h from Bay Area (SFO) or 6h from LA; Reno (RNO) is closest airport at 1.5h; I-80 chains required",
					},
				},
				{
					ID:              "northstar",
					RegionID:        "ca_north_tahoe",
					Name:            "Northstar California",
					Latitude:        39.2744,
					Longitude:       -120.1211,
					ElevationM:      2611,
					PassAffiliation: "epic",
					VerticalDropM:   610,
					LiftCount:       20,
					Metadata: map[string]string{
						"reputation":       "family-friendly, excellent grooming, ski-in/ski-out village, terrain parks",
						"terrain_character": "back side trees and steeps for experts; front side groomers for intermediates; Ritz-Carlton on hill",
						"access_notes":     "20min from Truckee (TKF) airport; 30min from Reno (RNO); I-267 off I-80",
					},
				},
				{
					ID:              "sugar_bowl",
					RegionID:        "ca_north_tahoe",
					Name:            "Sugar Bowl",
					Latitude:        39.3019,
					Longitude:       -120.3467,
					ElevationM:      2661,
					PassAffiliation: "independent",
					VerticalDropM:   649,
					LiftCount:       13,
					Metadata: map[string]string{
						"reputation":       "oldest Tahoe resort (1939), right on the Sierra divide, catches storms first, hidden gem",
						"terrain_character": "diverse terrain, good tree skiing, best positioned to catch NW storm track directly",
						"access_notes":     "I-80 Norden/Soda Springs exit; access road is short; one of easiest Tahoe resorts to reach",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "ca_south_tahoe",
				Name:                "South Lake Tahoe, CA/NV",
				Latitude:            38.9353,
				Longitude:           -119.9400,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "heavenly",
					RegionID:        "ca_south_tahoe",
					Name:            "Heavenly Mountain Resort",
					Latitude:        38.9353,
					Longitude:       -119.9400,
					ElevationM:      3066,
					PassAffiliation: "epic",
					VerticalDropM:   1068,
					LiftCount:       29,
					Metadata: map[string]string{
						"reputation":       "massive terrain straddling CA/NV, lake views, south-facing aspects dry fast after storms",
						"terrain_character": "Mott and Killebrew Canyons on Nevada side for expert skiing; lake views unmatched in Tahoe",
						"access_notes":     "gondola from South Lake Tahoe; 1h from Reno (RNO); south side of lake on US-50",
					},
				},
				{
					ID:              "kirkwood",
					RegionID:        "ca_south_tahoe",
					Name:            "Kirkwood Mountain Resort",
					Latitude:        38.6847,
					Longitude:       -120.0650,
					ElevationM:      2375,
					PassAffiliation: "epic",
					VerticalDropM:   787,
					LiftCount:       15,
					Metadata: map[string]string{
						"reputation":       "highest base in Tahoe, most consistent snowfall, best powder in the region, expert-heavy",
						"terrain_character": "Cirque and Sentinel Bowl for committed expert terrain; snow depth frequently exceeds all Tahoe neighbors",
						"access_notes":     "35min from South Lake Tahoe via CA-88; more remote than Heavenly; no lodging at base",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "ca_mammoth",
				Name:                "Mammoth Lakes, CA",
				Latitude:            37.6308,
				Longitude:           -119.0326,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "mammoth_mountain",
					RegionID:        "ca_mammoth",
					Name:            "Mammoth Mountain",
					Latitude:        37.6308,
					Longitude:       -119.0326,
					ElevationM:      3369,
					PassAffiliation: "ikon",
					VerticalDropM:   914,
					LiftCount:       25,
					Metadata: map[string]string{
						"reputation":       "top of the Sierra, massive snowfall years, season extends into June or July; LA crowd favorite",
						"terrain_character": "exposed summit with cornices and chutes; excellent tree skiing mid-mountain; all abilities served",
						"access_notes":     "Mammoth Yosemite Airport (MMH) has seasonal Alaska/United flights; 5h from LA via US-395",
					},
				},
			},
		},

		// ── Pacific Northwest ──────────────────────────────────────────────────

		{
			Region: domain.Region{
				ID:                  "wa_cascades",
				Name:                "Washington Cascades",
				Latitude:            47.7456,
				Longitude:           -121.5458,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "stevens_pass",
					RegionID:        "wa_cascades",
					Name:            "Stevens Pass",
					Latitude:        47.7456,
					Longitude:       -121.0956,
					ElevationM:      1803,
					PassAffiliation: "ikon",
					VerticalDropM:   533,
					LiftCount:       10,
					Metadata: map[string]string{
						"reputation":       "Seattle locals' mountain, consistent maritime snowfall, excellent tree skiing in storms",
						"terrain_character": "Seventh Heaven expert terrain, dense glades, wet Sierra Cement can be heavy — go right after storm",
						"access_notes":     "1.5h from Seattle via US-2; no lodging at base; road stays open in most storms",
					},
				},
				{
					ID:              "crystal_mountain",
					RegionID:        "wa_cascades",
					Name:            "Crystal Mountain",
					Latitude:        46.9283,
					Longitude:       -121.4742,
					ElevationM:      2278,
					PassAffiliation: "ikon",
					VerticalDropM:   914,
					LiftCount:       13,
					Metadata: map[string]string{
						"reputation":       "Washington's largest, Mt. Rainier views, highest summit in WA ski areas, quality powder",
						"terrain_character": "Southback side for expert powder, Front Side groomed, resort feels bigger than its lift count",
						"access_notes":     "2h from Seattle or Tacoma via WA-410; spur road to base off WA-410",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "wa_mt_baker",
				Name:                "Mt. Baker Area, WA",
				Latitude:            48.8600,
				Longitude:           -121.6650,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "mt_baker",
					RegionID:        "wa_mt_baker",
					Name:            "Mt. Baker Ski Area",
					Latitude:        48.8600,
					Longitude:       -121.6650,
					ElevationM:      1220,
					PassAffiliation: "independent",
					VerticalDropM:   457,
					LiftCount:       8,
					Metadata: map[string]string{
						"reputation":       "world record single-season snowfall (29m in 1999), low-key, no-frills, powder sanctuary",
						"terrain_character": "dense glades, chutes, best snowfall in lower-48 in big winters; small but deep",
						"access_notes":     "1.5h from Bellingham via WA-542; 2h from Vancouver BC; road ends at resort — no through traffic",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "or_cascades",
				Name:                "Oregon Cascades",
				Latitude:            43.9911,
				Longitude:           -121.6878,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "mt_bachelor",
					RegionID:        "or_cascades",
					Name:            "Mt. Bachelor",
					Latitude:        43.9911,
					Longitude:       -121.6878,
					ElevationM:      2764,
					PassAffiliation: "ikon",
					VerticalDropM:   915,
					LiftCount:       15,
					Metadata: map[string]string{
						"reputation":       "symmetrical volcano, wind can close summit, best powder on protected NW-facing chairs",
						"terrain_character": "top of volcano is expert wind-buffed territory; trees on lower mountain hold best powder",
						"access_notes":     "25min from Bend (BND) via Century Drive; Bend has regular service from major PNW hubs",
					},
				},
				{
					ID:              "mt_hood_meadows",
					RegionID:        "or_cascades",
					Name:            "Mt. Hood Meadows",
					Latitude:        45.3311,
					Longitude:       -121.6636,
					ElevationM:      2202,
					PassAffiliation: "independent",
					VerticalDropM:   701,
					LiftCount:       11,
					Metadata: map[string]string{
						"reputation":       "Portland's local hill, catches maritime storms directly off the Pacific, consistent snowfall",
						"terrain_character": "HRM Canyon for experts, wide groomed runs for intermediates; elevation means wetter snow",
						"access_notes":     "1.5h from Portland via US-26; OR-35 to OR-26 approach; road typically stays open",
					},
				},
			},
		},

		// ── Idaho ──────────────────────────────────────────────────────────────

		{
			Region: domain.Region{
				ID:                  "id_sun_valley",
				Name:                "Sun Valley Area, ID",
				Latitude:            43.6958,
				Longitude:           -114.3514,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "sun_valley",
					RegionID:        "id_sun_valley",
					Name:            "Sun Valley",
					Latitude:        43.6958,
					Longitude:       -114.3514,
					ElevationM:      2792,
					PassAffiliation: "independent",
					VerticalDropM:   1067,
					LiftCount:       18,
					Metadata: map[string]string{
						"reputation":       "America's first destination resort (1936), dry cold continental powder, celebrity playground",
						"terrain_character": "Bald Mountain is serious expert terrain; consistent cold dry powder unlike PNW resorts",
						"access_notes":     "Friedman Memorial Airport (SUN) in Hailey, 15min from resort; direct flights from major hubs seasonally",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "id_grand_targhee",
				Name:                "Grand Targhee Area, ID/WY",
				Latitude:            43.7883,
				Longitude:           -110.9469,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "grand_targhee",
					RegionID:        "id_grand_targhee",
					Name:            "Grand Targhee Resort",
					Latitude:        43.7883,
					Longitude:       -110.9469,
					ElevationM:      2743,
					PassAffiliation: "ikon",
					VerticalDropM:   610,
					LiftCount:       5,
					Metadata: map[string]string{
						"reputation":       "\"where the snow comes from\"; west side of Tetons catches storm track before Jackson; cult powder resort",
						"terrain_character": "Peaked Mountain snowcat skiing, consistent 10m+ annual snowfall, uncrowded even on powder days",
						"access_notes":     "1.5h from JAC airport via Driggs, ID; road can be challenging in big storms; worth every mile",
					},
				},
			},
		},

		// ── Northeast ─────────────────────────────────────────────────────────

		{
			Region: domain.Region{
				ID:                  "vt_central",
				Name:                "Vermont (Central)",
				Latitude:            44.5303,
				Longitude:           -72.7814,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "stowe",
					RegionID:        "vt_central",
					Name:            "Stowe Mountain Resort",
					Latitude:        44.5303,
					Longitude:       -72.7814,
					ElevationM:      1339,
					PassAffiliation: "epic",
					VerticalDropM:   720,
					LiftCount:       13,
					Metadata: map[string]string{
						"reputation":       "quintessential New England skiing, Mt. Mansfield is Vermont's highest peak, iconic Front Four",
						"terrain_character": "Front Four expert trails are genuinely steep for East; Spruce Peak for families; charm of the village",
						"access_notes":     "45min from Burlington (BTV) airport; I-89 to VT-100; village walkable from most lodging",
					},
				},
				{
					ID:              "sugarbush",
					RegionID:        "vt_central",
					Name:            "Sugarbush Resort",
					Latitude:        44.1367,
					Longitude:       -72.8961,
					ElevationM:      1197,
					PassAffiliation: "ikon",
					VerticalDropM:   793,
					LiftCount:       16,
					Metadata: map[string]string{
						"reputation":       "Mad River Valley, connected Lincoln Peak and Mt. Ellen, expert terrain rivals Stowe",
						"terrain_character": "Lincoln Peak has serious steep terrain; Mt. Ellen has better groomed cruisers; great tree skiing",
						"access_notes":     "45min from Burlington or 3h from Boston; VT-17 in from the valley",
					},
				},
				{
					ID:              "mad_river_glen",
					RegionID:        "vt_central",
					Name:            "Mad River Glen",
					Latitude:        44.1917,
					Longitude:       -72.9336,
					ElevationM:      1088,
					PassAffiliation: "independent",
					VerticalDropM:   549,
					LiftCount:       5,
					Metadata: map[string]string{
						"reputation":       "skier-owned cooperative, no snowboards, single chair, most challenging in-bounds in the East",
						"terrain_character": "\"ski it if you can\" — genuine ungroomed expert terrain; natural snow only; iconic single chair",
						"access_notes":     "VT-17 in Mad River Valley; 45min from Burlington; best when natural snowfall is recent and deep",
					},
				},
				{
					ID:              "killington",
					RegionID:        "vt_central",
					Name:            "Killington Resort",
					Latitude:        43.6045,
					Longitude:       -72.8201,
					ElevationM:      1292,
					PassAffiliation: "epic",
					VerticalDropM:   732,
					LiftCount:       22,
					Metadata: map[string]string{
						"reputation":       "Beast of the East, largest in Vermont, longest season, biggest vertical drop in East",
						"terrain_character": "Superstar trail holds snow longest in East; six interconnected mountains; strong snowmaking backup",
						"access_notes":     "3h from Boston; 4h from NYC; US-4 off I-89 or I-91; no ski-in/ski-out in most lodging",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "nh_white_mountains",
				Name:                "New Hampshire White Mountains",
				Latitude:            44.2567,
				Longitude:           -71.2936,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "wildcat",
					RegionID:        "nh_white_mountains",
					Name:            "Wildcat Mountain",
					Latitude:        44.2567,
					Longitude:       -71.2369,
					ElevationM:      1288,
					PassAffiliation: "epic",
					VerticalDropM:   655,
					LiftCount:       5,
					Metadata: map[string]string{
						"reputation":       "overlooking Tuckerman Ravine, challenging fall-line terrain, no frills, raw Northeast skiing",
						"terrain_character": "primarily expert/intermediate fall-line runs; winds can be fierce; go for the vibe and challenge",
						"access_notes":     "NH-16 in Pinkham Notch; 2.5h from Boston; Manchester (MHT) or Portland (PWM) airports",
					},
				},
				{
					ID:              "cannon",
					RegionID:        "nh_white_mountains",
					Name:            "Cannon Mountain",
					Latitude:        44.1572,
					Longitude:       -71.6961,
					ElevationM:      1289,
					PassAffiliation: "independent",
					VerticalDropM:   668,
					LiftCount:       9,
					Metadata: map[string]string{
						"reputation":       "state-owned, affordable, serious terrain, catches NW storm track on Franconia Ridge",
						"terrain_character": "steep expert terrain, tram access, ice is possible but new snow skis very well on the fall lines",
						"access_notes":     "I-93 exit 34C in Franconia Notch; 2.5h from Boston; Manchester (MHT) airport is closest",
					},
				},
				{
					ID:              "loon_mountain",
					RegionID:        "nh_white_mountains",
					Name:            "Loon Mountain",
					Latitude:        44.0228,
					Longitude:       -71.6219,
					ElevationM:      1067,
					PassAffiliation: "ikon",
					VerticalDropM:   518,
					LiftCount:       12,
					Metadata: map[string]string{
						"reputation":       "family-friendly, accessible from I-93, good snowmaking, busy on weekends from Boston",
						"terrain_character": "South Peak for intermediate terrain, North Peak for variety; strong snowmaking program",
						"access_notes":     "I-93 exit 32 in Lincoln, NH; 2h from Boston; most accessible major NH resort",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "me_western_mountains",
				Name:                "Western Maine Mountains",
				Latitude:            45.0953,
				Longitude:           -70.3139,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "sugarloaf",
					RegionID:        "me_western_mountains",
					Name:            "Sugarloaf",
					Latitude:        45.0953,
					Longitude:       -70.3139,
					ElevationM:      1291,
					PassAffiliation: "ikon",
					VerticalDropM:   820,
					LiftCount:       13,
					Metadata: map[string]string{
						"reputation":       "highest lift-served terrain in the East, above-treeline snowfields on the Snowfields, remote and worth it",
						"terrain_character": "Snowfields above treeline for experts, great tree skiing in storms, best big mountain feel in East",
						"access_notes":     "3h from Portland (PWM); remote by NE standards; Portland has good flight connections",
					},
				},
				{
					ID:              "sunday_river",
					RegionID:        "me_western_mountains",
					Name:            "Sunday River",
					Latitude:        44.4697,
					Longitude:       -70.8564,
					ElevationM:      972,
					PassAffiliation: "ikon",
					VerticalDropM:   610,
					LiftCount:       15,
					Metadata: map[string]string{
						"reputation":       "eight interconnected peaks, excellent snowmaking, most reliable East Coast resort for conditions",
						"terrain_character": "White Heat is one of East's steepest groomed trails; consistent quality across all eight peaks",
						"access_notes":     "3h from Boston, 2.5h from Portland (PWM); US-2 to Sunday River Road in Newry, ME",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "ny_adirondacks",
				Name:                "New York Adirondacks",
				Latitude:            44.3658,
				Longitude:           -73.9008,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "whiteface",
					RegionID:        "ny_adirondacks",
					Name:            "Whiteface Mountain",
					Latitude:        44.3658,
					Longitude:       -73.9008,
					ElevationM:      1483,
					PassAffiliation: "epic",
					VerticalDropM:   1007,
					LiftCount:       11,
					Metadata: map[string]string{
						"reputation":       "highest vertical in the East, 1980 Olympics venue in Lake Placid, catches lake-effect from Lake Champlain",
						"terrain_character": "steep fall-line runs, intimidating top section, Lake Placid elevation means cold temperatures",
						"access_notes":     "30min from Plattsburgh (PBG) or 3.5h from Albany; Burlington (BTV) is 1h across the lake",
					},
				},
				{
					ID:              "gore_mountain",
					RegionID:        "ny_adirondacks",
					Name:            "Gore Mountain",
					Latitude:        43.6736,
					Longitude:       -74.0047,
					ElevationM:      1106,
					PassAffiliation: "epic",
					VerticalDropM:   533,
					LiftCount:       14,
					Metadata: map[string]string{
						"reputation":       "state-owned, affordable, quality terrain for the money, catches storms from the west",
						"terrain_character": "North Slope expert terrain is legit; groomed runs are wide and varied; good value",
						"access_notes":     "3h from NYC or Albany; I-87 to NY-28; no real base village — stay in North Creek",
					},
				},
			},
		},

		// ── British Columbia ───────────────────────────────────────────────────

		{
			Region: domain.Region{
				ID:                  "bc_whistler",
				Name:                "Whistler/Blackcomb, BC",
				Latitude:            50.1158,
				Longitude:           -122.9544,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "CA",
			},
			Resorts: []domain.Resort{
				{
					ID:              "whistler_blackcomb",
					RegionID:        "bc_whistler",
					Name:            "Whistler Blackcomb",
					Latitude:        50.1158,
					Longitude:       -122.9544,
					ElevationM:      2284,
					PassAffiliation: "epic",
					VerticalDropM:   1530,
					LiftCount:       37,
					Metadata: map[string]string{
						"reputation":       "largest ski resort in North America, world-class in every category, 2010 Olympics venue",
						"terrain_character": "Spanky's Ladder, Blackcomb Glacier, Couloir Extreme; something for everyone at scale",
						"access_notes":     "2h from Vancouver (YVR) via Sea-to-Sky Hwy (BC-99); scenic but can be slow in storms",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "bc_interior",
				Name:                "Interior British Columbia (Selkirks/Rockies)",
				Latitude:            51.0000,
				Longitude:           -118.2000,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "CA",
			},
			Resorts: []domain.Resort{
				{
					ID:              "revelstoke",
					RegionID:        "bc_interior",
					Name:            "Revelstoke Mountain Resort",
					Latitude:        51.0000,
					Longitude:       -118.1667,
					ElevationM:      2225,
					PassAffiliation: "epic",
					VerticalDropM:   1713,
					LiftCount:       10,
					Metadata: map[string]string{
						"reputation":       "greatest vertical in North America, legendary deep Selkirk powder, growing but still relatively quiet",
						"terrain_character": "North Bowl and Ripper chairs access extreme terrain; bottom-to-top vertical skiing is unmatched",
						"access_notes":     "3h from Kelowna (YLW) or Kamloops (YKA); Trans-Canada Hwy to Rogers Pass — can close in avalanche control",
					},
				},
				{
					ID:              "kicking_horse",
					RegionID:        "bc_interior",
					Name:            "Kicking Horse Mountain Resort",
					Latitude:        51.2969,
					Longitude:       -117.0478,
					ElevationM:      2450,
					PassAffiliation: "epic",
					VerticalDropM:   1260,
					LiftCount:       5,
					Metadata: map[string]string{
						"reputation":       "expert-dominated, consistent deep powder in the Rockies, four-person gondola access to top",
						"terrain_character": "CPR Ridge and Bowl Over are commitment terrain; resort skews heavily expert",
						"access_notes":     "30min from Golden, BC; 3h from Banff; small local airport in Golden; usually drive from Calgary (YYC)",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "bc_okanagan",
				Name:                "Okanagan Highlands, BC",
				Latitude:            49.7500,
				Longitude:           -119.0833,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "CA",
			},
			Resorts: []domain.Resort{
				{
					ID:              "big_white",
					RegionID:        "bc_okanagan",
					Name:            "Big White Ski Resort",
					Latitude:        49.7192,
					Longitude:       -118.9414,
					ElevationM:      2319,
					PassAffiliation: "epic",
					VerticalDropM:   777,
					LiftCount:       16,
					Metadata: map[string]string{
						"reputation":       "famous fog and \"snow ghosts\" (trees encased in rime ice), dry interior powder, ski-in/ski-out village",
						"terrain_character": "varied terrain for all levels, consistently cold and dry snow compared to coastal BC, excellent glades",
						"access_notes":     "1h from Kelowna (YLW); Kelowna has good domestic connections; BC-33 to resort road",
					},
				},
				{
					ID:              "silver_star",
					RegionID:        "bc_okanagan",
					Name:            "Silver Star Mountain Resort",
					Latitude:        50.3583,
					Longitude:       -119.0583,
					ElevationM:      1915,
					PassAffiliation: "epic",
					VerticalDropM:   759,
					LiftCount:       12,
					Metadata: map[string]string{
						"reputation":       "colorful Victorian village, cold dry Okanagan powder, excellent cross-country network adjacent",
						"terrain_character": "Putnam Creek expert glades, Silver Queen intermediate, Vance Creek beginner; balanced mountain",
						"access_notes":     "22km from Vernon, BC; 1.5h from Kelowna (YLW); BC-97 to Silver Star Road",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "bc_powder_highway",
				Name:                "BC Powder Highway (East Kootenays)",
				Latitude:            49.5000,
				Longitude:           -115.0833,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "CA",
			},
			Resorts: []domain.Resort{
				{
					ID:              "fernie",
					RegionID:        "bc_powder_highway",
					Name:            "Fernie Alpine Resort",
					Latitude:        49.4633,
					Longitude:       -115.0897,
					ElevationM:      1849,
					PassAffiliation: "epic",
					VerticalDropM:   857,
					LiftCount:       10,
					Metadata: map[string]string{
						"reputation":       "legendary for storm cycle powder, five alpine bowls, charming Fernie town, cult status",
						"terrain_character": "Lizard Bowl, Currie Bowl, Siberia Bowl for expert powder; trees hold snow exceptionally well",
						"access_notes":     "1h from Cranbrook (YXC); 3h from Calgary (YYC); Crowsnest Pass route from Alberta",
					},
				},
				{
					ID:              "panorama",
					RegionID:        "bc_powder_highway",
					Name:            "Panorama Mountain Resort",
					Latitude:        50.4583,
					Longitude:       -116.2417,
					ElevationM:      2394,
					PassAffiliation: "independent",
					VerticalDropM:   1219,
					LiftCount:       10,
					Metadata: map[string]string{
						"reputation":       "massive vertical, underrated, ski-in/ski-out village, fewer crowds than Fernie or Revelstoke",
						"terrain_character": "Taynton Bowl for experts, long groomers top to bottom, consistent cold powder in Columbia Valley",
						"access_notes":     "18km from Invermere, BC; 3h from Calgary (YYC); easiest via BC-93 from Alberta",
					},
				},
			},
		},

		// ── Alberta ───────────────────────────────────────────────────────────

		{
			Region: domain.Region{
				ID:                  "ab_banff",
				Name:                "Banff Area, AB",
				Latitude:            51.1784,
				Longitude:           -115.5708,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "CA",
			},
			Resorts: []domain.Resort{
				{
					ID:              "lake_louise",
					RegionID:        "ab_banff",
					Name:            "Lake Louise Ski Resort",
					Latitude:        51.4411,
					Longitude:       -116.1550,
					ElevationM:      2637,
					PassAffiliation: "epic",
					VerticalDropM:   991,
					LiftCount:       10,
					Metadata: map[string]string{
						"reputation":       "largest ski area in Canada, spectacular Rocky Mountain backdrop, consistent cold powder",
						"terrain_character": "Larch and Ptarmigan bowls for expert powder, front side groomers with Château backdrop, backside runs",
						"access_notes":     "45min from Banff townsite, 1.5h from Calgary (YYC); Trans-Canada Hwy; shuttle from Banff available",
					},
				},
				{
					ID:              "sunshine_village",
					RegionID:        "ab_banff",
					Name:            "Sunshine Village",
					Latitude:        51.1222,
					Longitude:       -115.7628,
					ElevationM:      2730,
					PassAffiliation: "epic",
					VerticalDropM:   1070,
					LiftCount:       12,
					Metadata: map[string]string{
						"reputation":       "highest base elevation of Banff resorts, Delirium Dive requires avalanche safety gear, deep continental powder",
						"terrain_character": "Delirium Dive and Wild West for committed experts; Goat's Eye for expert powder days",
						"access_notes":     "20min from Banff on Sunshine Road; gondola access from parking lot; 1.5h from Calgary (YYC)",
					},
				},
			},
		},

		{
			Region: domain.Region{
				ID:                  "ab_jasper",
				Name:                "Jasper Area, AB",
				Latitude:            52.8737,
				Longitude:           -118.0814,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "CA",
			},
			Resorts: []domain.Resort{
				{
					ID:              "marmot_basin",
					RegionID:        "ab_jasper",
					Name:            "Marmot Basin",
					Latitude:        52.7769,
					Longitude:       -118.0600,
					ElevationM:      2612,
					PassAffiliation: "independent",
					VerticalDropM:   900,
					LiftCount:       9,
					Metadata: map[string]string{
						"reputation":       "Jasper National Park setting, uncrowded, reliable cold powder, local secret among Alberta skiers",
						"terrain_character": "varied terrain across multiple exposures, good powder preservation in cold Rockies climate",
						"access_notes":     "20min from Jasper townsite; 4h from Edmonton (YEG) or 6h from Calgary (YYC); Icefields Parkway access",
					},
				},
			},
		},

		// ── Alaska ────────────────────────────────────────────────────────────

		{
			Region: domain.Region{
				ID:                  "ak_alyeska",
				Name:                "Alyeska / Girdwood, AK",
				Latitude:            60.9572,
				Longitude:           -149.1083,
				FrictionTier:        domain.FrictionFlight,
				NearThresholdCM:     61,
				ExtendedThresholdCM: 91,
				Country:             "US",
			},
			Resorts: []domain.Resort{
				{
					ID:              "alyeska",
					RegionID:        "ak_alyeska",
					Name:            "Alyeska Resort",
					Latitude:        60.9572,
					Longitude:       -149.1083,
					ElevationM:      1207,
					PassAffiliation: "independent",
					VerticalDropM:   869,
					LiftCount:       9,
					Metadata: map[string]string{
						"reputation":       "Alaska skiing accessible from Anchorage, massive annual snowfall, tram to 2500ft, dramatic Chugach backdrop",
						"terrain_character": "North Face accessed by tram is serious expert terrain; front side suits all levels; night skiing available",
						"access_notes":     "40min from Anchorage (ANC) via Seward Hwy and Alyeska Hwy; Anchorage has direct flights from most US hubs",
					},
				},
			},
		},
	}
}
